### ISSUE TITLE
Agile practices

### ISSUE THREAD

**Issue by Kiopp** [Kiopp/Dungeon-Crawler-Game#100]
Create an issue regarding what agile practices you have employed in your project and comment the practices that you have recognised, with a very brief explanation.

**Comment by Vencilo** [comment]
We have used a Kanban board to follow the project, which has allowed us to see where we are with the project, what is being worked on, what needs to be done, and what has been completed. It has improved our workflow and collaboration within the group, ensuring that everyone was up to speed with the project's status.

**Comment by Vencilo** [comment]
We have tried to hold weekly meetings discussing what has been completed, what everyone is currently working on and what needs to be done for the coming week. During these meetings we would also brainstorm ideas, prioritize tasks, and help each other with questions or coding. This helped us a lot with our collaboration, workflow, and the continuous progression of the project.

**Comment by Vencilo** [comment]
We also used continuous integration. We regularly committed changes and merged them into the main branch, ensuring that everyone could track our progress and access the latest code and changes. Alongside this we integrated automated testing, allowing us to regularly test our code and ensure the program could compile properly. 

This enabled us to detect and solve issues early, preventing them to stack up towards the end of the development. By fixing these errors as they came, we were able to maintain a stable production environment and kept the main branch up to date. This gave us more test coverage and more regular testing to ensure that new changes didn't break existing functionality, as we could always compile and build our program successfully.

**Comment by Vencilo** [comment]
We sometimes worked in pairs on the same computer, which helped ensure that different parts of the project worked properly together and made merging code easier. This also improved code quality, as two people were reviewing it simultaneously while writing. Additionally, it enhanced collaboration, improved team members knowledge about the program and led to great suggestions for improvements.
