### ISSUE TITLE
Thoughts for Presentation 2

### ISSUE THREAD

**Issue by majo22wx** [Kiopp/Dungeon-Crawler-Game#144]
### 1. Use of Continuous Integration (CI): describe how you have done it, which tools you have used, and what benefits you have experienced.

We're using githubs actions and workflows. We use a CI framework called GameCI for testing and building the project. We also run a linter called super linter provided by github.

### 2. Use of Pull Requests and Code Review: describe how you have done it, how it has helped you to improve the quality of the code, and how it has helped you to collaborate with your team members. 

We started out all using different feature branches. This workflow quickly ran into integration and merging problems because of the unity project files being complex. We've since been striving to use shortlived branches and pullrequests in our development process. This has led to a general improvement in our development process and has especially made integration less of a problem.

### 8. Software Licensing: describe which license you have chosen and why you have chosen it. You should also describe whether you have made your project public or kept it private.

**Comment by Kiopp** [comment]
- Introduce and demo the project. 
- Provide a brief description of the project
- The technologies used
- The scope of the project.
