### ISSUE TITLE
Create few issues on using GRASP which are “closed” with an associated implementation

### ISSUE THREAD

**Issue by Kiopp** [Kiopp/Dungeon-Crawler-Game#89]
This also needs to be documented in some way. A short description of what pattern is used and why.

**Comment by Vencilo** [comment]
Added the IBattleEntity interface to improve cohesion and coupling of the script. It also follows the GRASP principle in ensuring the battle entity classes has one responsibility, handling battle entities. The interface help ensuring the single responsibility principle.

**Comment by Kiopp** [comment]
From #36 the GameInput class is an example of the Controller pattern. As it handles input events from PlayerInputActions and translates them into actions within the game. It controls the flow of the game based on user input.

GameInput also demonstrates the Information Expert pattern. It holds information about movement and rotation delays, as well as the current state of movement/rotation. Since it has this information, it's also responisible for deciding when it is appropriate to initiate a move or rotation.

GameInput is fairly loosely coupled with other classes. Which makes it have low coupling. Since it only interacts with a simple GameObject reference, which could be any object that should be controlled by the player.
